- hosts: web_server
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Install docker compose
      apt:
        name: docker-compose
        state: present

    - name: Start nginx using docker compose
      command: docker-compose up -d
      args:
        chdir: ./docker-compose.yml